Repository kakao-tech-campus-3rd-step3/Team6_BE, pull requests merged in 2025-09, with the labels that each got.

#31 feat/#24 - Stomp 를 통한 Waiting Room 커넥션 관리 및 사용자 토큰을 통한 접근 추가
  build.gradle
  src/main/java/com/icebreaker/be/application/room/RoomService.java
  src/main/java/com/icebreaker/be/application/room/WaitingRoomEventPublisher.java
  src/main/java/com/icebreaker/be/application/room/WaitingRoomFullEvent.java
  src/main/java/com/icebreaker/be/application/room/WaitingRoomNotifier.java
  src/main/java/com/icebreaker/be/application/room/WaitingRoomService.java
  src/main/java/com/icebreaker/be/application/user/UserService.java
  src/main/java/com/icebreaker/be/application/user/dto/UserIdWithTokenResponse.java
  src/main/java/com/icebreaker/be/domain/room/Participant.java
  src/main/java/com/icebreaker/be/domain/room/Room.java
  src/main/java/com/icebreaker/be/domain/room/WaitingRoom.java
  src/main/java/com/icebreaker/be/domain/room/WaitingRoomIdGenerator.java
  src/main/java/com/icebreaker/be/domain/room/WaitingRoomRepository.java
  src/main/java/com/icebreaker/be/domain/room/WaitingRoomStatus.java
  src/main/java/com/icebreaker/be/global/annotation/CurrentUser.java
  src/main/java/com/icebreaker/be/global/config/WebSocketConfig.java
  src/main/java/com/icebreaker/be/global/exception/ErrorCode.java
  src/main/java/com/icebreaker/be/global/interceptor/JwtChannelInterceptor.java
  src/main/java/com/icebreaker/be/global/interceptor/StompPrincipal.java
  src/main/java/com/icebreaker/be/global/resolver/CurrentUserArgumentResolver.java
  src/main/java/com/icebreaker/be/infra/generator/InMemoryWaitingRoomIdGenerator.java
  src/main/java/com/icebreaker/be/infra/jwt/JwtProvider.java
  src/main/java/com/icebreaker/be/infra/persistence/InMemoryWaitingRoomRepository.java
  src/main/java/com/icebreaker/be/presentation/room/WaitingRoomController.java
  src/main/java/com/icebreaker/be/presentation/user/UserApiDocs.java
  src/main/java/com/icebreaker/be/presentation/user/UserController.java
  src/main/resources/application.yaml
  src/test/java/com/icebreaker/be/application/room/RoomServiceTest.java
  src/test/java/com/icebreaker/be/application/room/WaitingRoomEventPublisherTest.java
  src/test/java/com/icebreaker/be/application/room/WaitingRoomFullEventTest.java
  src/test/java/com/icebreaker/be/application/room/WaitingRoomNotifierTest.java
  src/test/java/com/icebreaker/be/application/room/WaitingRoomServiceTest.java
  src/test/java/com/icebreaker/be/application/user/UserServiceTest.java
  src/test/java/com/icebreaker/be/domain/question/QuestionRepositoryTest.java
  src/test/java/com/icebreaker/be/domain/room/RoomRepositoryTest.java
  src/test/java/com/icebreaker/be/domain/room/WaitingRoomTest.java
  src/test/java/com/icebreaker/be/domain/user/UserRepositoryTest.java
  src/test/java/com/icebreaker/be/presentation/question/QuestionControllerTest.java
  src/test/java/com/icebreaker/be/presentation/user/UserControllerTest.java
Labels: 📌Feature, 😎Enhancement, P2 : Medium

#33 refactor/#30 - Collection Framework 기반의 Repository 를 Valkey 로 마이그레이션
  build.gradle
  deploy.sh
  src/main/java/com/icebreaker/be/application/room/WaitingRoomService.java
  src/main/java/com/icebreaker/be/domain/room/WaitingRoom.java
  src/main/java/com/icebreaker/be/domain/room/WaitingRoomRepository.java
  src/main/java/com/icebreaker/be/domain/room/WaitingRoomRepositoryCustom.java
  src/main/java/com/icebreaker/be/global/runner/RedisConnectionCheckRunner.java
  src/main/java/com/icebreaker/be/infra/config/RedisConfig.java
  src/main/java/com/icebreaker/be/infra/persistence/InMemoryWaitingRoomRepository.java
  src/main/java/com/icebreaker/be/infra/persistence/RedisWaitingRoomRepository.java
  src/main/resources/application.yaml
  src/test/java/com/icebreaker/be/application/room/WaitingRoomServiceTest.java
Labels: 😎Enhancement, P2 : Medium

#62 docs/#44 - 최신 ERD 반영
  docs/er-diagram.png
  docs/erd-diagram.png
Labels: P3 : Low

#68 bug/#67 - caddy가 전달하는 forward 헤더 신뢰하도록 변경
  src/main/resources/application.yaml
Labels: 🐞Bug, P2 : Medium
